### ISSUE TITLE
vite + antd-mobile的问题

### ISSUE THREAD

**Issue by Jackson-p** [0ahz/vite-plugin-babel-import#3]
大佬，先start为敬，使用过程中遇到个问题
![image](https://user-images.githubusercontent.com/20417123/112287768-acc67580-8cc7-11eb-8cf0-84727541525a.png)
dev模式没问题
但是本地build的时候会显示
![image](https://user-images.githubusercontent.com/20417123/112288005-e4352200-8cc7-11eb-9d20-5240dd43c746.png)
虽然也编译成功了，但是最后起静态服务去访问页面的时候会报
![image](https://user-images.githubusercontent.com/20417123/112288090-f911b580-8cc7-11eb-882d-3e8b5f98e23f.png)

这样的错误，把Toast内容里面注释掉就不会报这个错，我以为是预编译的问题，🧎‍♂️🧎‍♀️，引了这个插件也没成功，style的回调也没打印出name

**Comment by tangdw** [comment]
@Jackson-p    应该不是插件的问题，我手动引入

import Picker from 'antd-mobile/es/picker'
import 'antd-mobile/es/picker/style'

访问打包的资源还是有那个问题

Uncaught TypeError: Failed to resolve module specifier "indexof". Relative references must start with either "/", "./", or "../".

**Comment by Jackson-p** [comment]
> @Jackson-p 应该不是插件的问题，我手动引入
> 
> import Picker from 'antd-mobile/es/picker'
> import 'antd-mobile/es/picker/style'
> 
> 访问打包的资源还是有那个问题
> 
> Uncaught TypeError: Failed to resolve module specifier "indexof". Relative references must start with either "/", "./", or "../".

嗯嗯 这个问题后来解决了 不是插件的问题 忘记关issue了 感谢感谢

**Comment by shuyanzi** [comment]
> > @Jackson-p 应该不是插件的问题，我手动引入
> > import Picker from 'antd-mobile/es/picker'
> > import 'antd-mobile/es/picker/style'
> > 访问打包的资源还是有那个问题
> > Uncaught TypeError: Failed to resolve module specifier "indexof". Relative references must start with either "/", "./", or "../".
> 
> 嗯嗯 这个问题后来解决了 不是插件的问题 忘记关issue了 感谢感谢

怎么解决的呢？

**Comment by Jackson-p** [comment]
> > > @Jackson-p 应该不是插件的问题，我手动引入
> > > import Picker from 'antd-mobile/es/picker'
> > > import 'antd-mobile/es/picker/style'
> > > 访问打包的资源还是有那个问题
> > > Uncaught TypeError: Failed to resolve module specifier "indexof". Relative references must start with either "/", "./", or "../".
> > 
> > 
> > 嗯嗯 这个问题后来解决了 不是插件的问题 忘记关issue了 感谢感谢
> 
> 怎么解决的呢？

build就是成功不了，说错了，不是解决了

**Comment by abear-eatsfish** [comment]
`npm install indexof`
https://github.com/vitejs/vite/issues/2670#issuecomment-822230172
