### ISSUE TITLE
import {  locale } from 'element-plus'   can not work

### ISSUE THREAD

**Issue by HongqingCao** [0ahz/vite-plugin-babel-import#5]
The default locale of Element Plus is English. If we want to use another language, need to do some i18n configuration。Through the Element Plus website ，we  can set

main.js

import { ElButton, locale } from 'element-plus'
import lang from 'element-plus/lib/locale/lang/zh-cn'
import 'dayjs/locale/zh-cn'

locale(lang)

vite.config.js

  vitePluginImport([
    {
      libraryName: 'element-plus',
      libraryDirectory: 'es',
      style(name) {
        return `element-plus/lib/theme-chalk/${name}.css`;
      },
    }
  ])

'element-plus/lib/theme-chalk/locale.css'   this file  inexistence,   so will [vite] Internal server error。

I hope I can improve on this babel，thank you~

**Comment by 0ahz** [comment]
Thanks for the bug report! 

fixed by  v2.0.3

```js
{
    libraryName: 'element-plus',
    libraryDirectory: 'es',
    style(name) {
      return `element-plus/lib/theme-chalk/${name}.css`;
    },
    ignoreStyles: ['locale'],
},
```

or

```js
{
    libraryName: 'element-plus',
    libraryDirectory: 'es',
    style(name) {
      if (name === 'locale') return;
      return `element-plus/lib/theme-chalk/${name}.css`;
    },
},
```
